### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by neha0ptimus** [neha0ptimus/misc_dive#2]
10/22/2018

- [x] Data Analysis Learning Curve all models
- [ ] Dynamic Threshold for various metrics - research
- [ ] Nested Cross Validation
- [ ] Prediction Interval for Logistic Regression

10/23/2018
- [ ] Plan for Learning Curve - Literature Review, think through stuff
